services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cobracerta
      POSTGRES_PASSWORD: cobracerta
      POSTGRES_DB: cobracerta
    ports:
      - "5432:5432"
    volumes:
      - cobracerta_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - cobracerta_redis_data:/data

volumes:
  cobracerta_postgres_data:
  cobracerta_redis_data:
